#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"

# Fetch dotbot: as a submodule if this is a git repo, otherwise plain clone
if [ ! -f "${DOTBOT_DIR}/${DOTBOT_BIN}" ]; then
  if [ -d .git ]; then
    git submodule update --init --recursive "${DOTBOT_DIR}"
  else
    git clone https://github.com/anishathalye/dotbot "${DOTBOT_DIR}"
  fi
fi

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
